/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_revo_aesrsa_JniUtil */

#ifndef _Included_com_revo_aesrsa_JniUtil
#define _Included_com_revo_aesrsa_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_revo_aesrsa_JniUtil
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_revo_aesrsa_JniUtil_getString
  (JNIEnv *, jobject);

/*
 * Class:     com_revo_aesrsa_JniUtil
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_revo_aesrsa_JniUtil_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_revo_aesrsa_JniUtil
 * Method:    encrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_revo_aesrsa_JniUtil_encrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_revo_aesrsa_JniUtil
 * Method:    decrypt
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_revo_aesrsa_JniUtil_decrypt
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_revo_aesrsa_JniUtil
 * Method:    getKeyValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_revo_aesrsa_JniUtil_getKeyValue
  (JNIEnv *, jobject);

/*
 * Class:     com_revo_aesrsa_JniUtil
 * Method:    getIv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_revo_aesrsa_JniUtil_getIv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
